development:
  access_key_id: AKIAIRUWPYD4BBCNI7IA
  secret_access_key: 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

production:
  access_key_id: ENV["AWS_ACCESS_KEY_ID"]
  secret_access_key: ENV["AWS_SECRET_KEY_SECRET"]
